[package]
name = "cone_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15"
itertools = "0.10.0"
lair = "0.5.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }